server:
  region: "EU"

db:
  host: "localhost"
  username: "tbd"
  password: "tbd"
  synchronize: true
  url: "mongodb://localhost/carrental1"

jwt:
  secret: "topSecret51"

auth:
  url: "http://localhost:3000/auth"
